### ISSUE TITLE
Information relating to approvers missing from documentation

### ISSUE THREAD

**Issue by rjcoupe** [trstringer/manual-approval#107]
I don't believe it's clarified anywhere in the documentation that the approvers specified must have access to the repo. While this isn't an impossible-to-guess step to take, the error resulting from this step not being taken is pretty opaque:

```422 Validation Failed [{Resource:Issue Field:assignees Code:invalid Message:}]```

IMHO it would be worth adding a note to the docs confirming that access for approvers to the repo is a step requiring taking.

**Comment by trstringer** [comment]
This is in the [readme](https://github.com/trstringer/manual-approval#usage)! You can see it mentioned in the `approvers` documentation.
