### ISSUE TITLE
422 validation failed

### ISSUE THREAD

**Issue by yanivg10** [trstringer/manual-approval#127]
Started getting this error when creating an issue through the workflow. This worked a couple of weeks ago, so I'm wondering what has changed and how to resolve this. I have not changed anything in the repo setup.

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.
error creating issue: POST https://api.github.com/repos/org/repo/issues: 422 Validation Failed [{Resource:Issue Field:assignees Code:invalid Message:}]

**Comment by yanivg10** [comment]
I am closing this issue, as I found a solution based on a similar issue that was published here.

**Comment by StevenBeasley-Beam** [comment]
What was the solution?
