### ISSUE TITLE
Support GitHub teams as a value for the "approvers" property

### ISSUE THREAD

**Issue by IdanYaffe** [trstringer/manual-approval#14]
Hello,
Thanks so much for this action! It's really great!
I would love it if we could set a GH team as the approver instead of specifying each user.

**Comment by trstringer** [comment]
Thanks for the suggestion! I think that's a great idea and I'll add that to the backlog.

**Comment by equals215** [comment]
Is this implemented? I'd love to use a team to approve

**Comment by trstringer** [comment]
Working on this now, should have it released in the next few days!

**Comment by trstringer** [comment]
Reopening as this issue is not resolved yet.

**Comment by trstringer** [comment]
This has been completed and tested in [v1.6.0](https://github.com/trstringer/manual-approval/releases/tag/v1.6.0)! This feature is [documented in the README](https://github.com/trstringer/manual-approval#org-team-approver).
