### ISSUE TITLE
Specify timeout duration when waiting for approval

### ISSUE THREAD

**Issue by jpike88** [trstringer/manual-approval#15]
There should be a way to allow the action to auto-timeout after for example 5 minutes

**Comment by trstringer** [comment]
Great idea! Added to the backlog.

**Comment by IdanYaffe** [comment]
@jpike88 @trstringer - in order to achieve this, I've set that action within a dedicated job in my workflow and am using the native GH capability of setting a timeout for that job like such:

production_gate:
    needs: [name_of_the_first_job]
    name: 'production gate'    
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        **timeout-minutes: 5**
        with:
          secret: <token>
          approvers: user1, user2
          minimum-approvals: 1

**Comment by trstringer** [comment]
That's actually a really good point, @IdanYaffe. Thank you for bringing that up! And with version 1.3+ when a workflow is cancelled it should close the issue.'

@jpike88, let me know if that fulfills your requirements!

**Comment by jpike88** [comment]
works for me! probably worth mentioning this `timeout-minutes` trick in the backlog
