### ISSUE TITLE
State the limitations and considerations

### ISSUE THREAD

**Issue by trstringer** [trstringer/manual-approval#2]
The readme should reflect the following limitations and considerations:

* While the workflow is paused, it will take a concurrent job spot
* A job is only allowed to run for a maximum of 6 hours and then it'll be failed
* The paused workflow is still compute that is running that could incur costs like any other idling VM

More information [here on GitHub docs](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits).

**Comment by unfor19** [comment]
@trstringer thanks for that, the third bullet point is a deal-breaker for me.
I thought that this action solves exactly this issue - "wait without using compute" :\

**Comment by trstringer** [comment]
Totally understand. That is the primary drawback, unfortunately. Thanks for the feedback!
