### ISSUE TITLE
Not working on MacOs container

### ISSUE THREAD

**Issue by cinder92** [trstringer/manual-approval#20]
Hello thanks for your plugin, how can we support mac os?
![Screen Shot 2022-06-13 at 19 20 07](https://user-images.githubusercontent.com/4725556/173468090-83467575-bec6-4013-92f9-f3e43d11e8f5.png)

**Comment by trstringer** [comment]
Yes! Thank you for creating this issue. I'll look into this.

**Comment by Bwvolleyball** [comment]
I was hoping to help with this issue, but it seems that actions that run as docker containers may only support Linux: https://docs.github.com/en/actions/creating-actions/about-custom-actions#types-of-actions

**Comment by trstringer** [comment]
This does in fact look like the case. Closing this now as it doesn't look like a possibility.
