### ISSUE TITLE
Enterprise edition privatization deployment is supported, and you can specify a domain name.

### ISSUE THREAD

**Issue by xinghaohao** [trstringer/manual-approval#37]
Enterprise edition privatization deployment is supported, and you can specify a domain name.
Currently, only the default github.com is supported, and the domain name of the enterprise version of the privatization deployment is not supported.

![image](https://user-images.githubusercontent.com/68051628/182280148-d40b6eea-7e52-4603-9f0f-3aaf8cea8076.png)

**Comment by xinghaohao** [comment]
URL: https://github.com/ORG/REPO/actions/runs/157925

Required approvers: [user]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.
error creating issue: POST https://api.github.com/repos/ORG/REPO/issues: 401 Bad credentials []

**Comment by jrkarnes** [comment]
Seconding this issue.

**Comment by trstringer** [comment]
This should be fixed in #52! I'll create a new release so that you can use this new feature. Thanks!
