### ISSUE TITLE
Trim whitespace from usernames. 

### ISSUE THREAD

**Issue by TroyWitthoeft** [trstringer/manual-approval#43]
Github's username policies don't allow spaces.   Can we update our code to trim them from usernames? 

![image](https://user-images.githubusercontent.com/1102958/185801834-b9e56344-d9b1-4a4c-99d7-17e148e6afb8.png)

Since we know usernames won't have spaces and we also know that people tend to enter spaces after commas, let's update our code to trim spaces from usernames?

This way if a user enters 
    `approvers: User1, User2, User3`
It will still work.  Currently it fails because we are searching for usernames that literally start with a space.

**Comment by TroyWitthoeft** [comment]
Created PR https://github.com/trstringer/manual-approval/pull/44

**Comment by trstringer** [comment]
Fixed in #44. Thank you!
