### ISSUE TITLE
Not working on a windows container

### ISSUE THREAD

**Issue by atlassian-natchiar** [trstringer/manual-approval#45]

**Comment by trstringer** [comment]
Hello, and thank you for opening this issue! I don't currently have the bandwidth or experience to add Windows containers support, but I would love a PR to include it in the project!

**Comment by Bwvolleyball** [comment]
I was hoping to help with this issue, but it seems that actions that run as docker containers may only support Linux: https://docs.github.com/en/actions/creating-actions/about-custom-actions#types-of-actions

**Comment by trstringer** [comment]
Thanks! Closing as it seems like this is not possible.
