### ISSUE TITLE
Manual approval doesn't work between steps for workflow

### ISSUE THREAD

**Issue by yashwanth-bit** [trstringer/manual-approval#53]
Hi Trstringer,

I am trying to use trstringer/manual-approval@v1 between workflow,however, it complains:
Attempting to expand user say-way/Torsten Sprenger as a group (may not succeed)
GET https://api.github.com/orgs/say-way/teams/Torsten%20Sprenger/members: 404 Not Found []
Attempting to expand user say-way/saywaydeploy as a group (may not succeed)
GET https://api.github.com/orgs/say-way/teams/saywaydeploy/members: 404 Not Found []
Creating issue in repo say-way/analytics-api with the following content:
Title: Manual approval required for workflow run 3338938915
Approvers: [Torsten Sprenger saywaydeploy]
Body:
Workflow is pending manual review.
URL: https://github.com/say-way/analytics-api/actions/runs/3338938915

Required approvers: [Torsten Sprenger saywaydeploy]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.
error creating issue: POST https://api.github.com/repos/say-way/analytics-api/issues: 410 Issues are disabled for this repo []

Here is the workflow:

deploy-demo:
    needs: build-and-push
    name: deployment in demo cluster
    environment: demo
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      
    env:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      username: ${{ secrets.USERNAME }}
      secret: ${{ secrets.DEPLOY_PAT }}
      ssh-key: ${{ secrets.SSHKEY }}
      
    steps:
      - name: Approval Demo
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ secrets.PACKAGE_PAT }}
          approvers: DevOps
          minimum_approvals: 1

      - name: Get Login to AWS ECR
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.ROLE_ASSUME }}
          aws-region: eu-central-1
          role-session-name: OIDCSession
          audience: sts.amazonaws.com
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

**Comment by trstringer** [comment]
> 410 Issues are disabled for this repo

It looks like your repo doesn't have issues enabled. This workflow requires the use of issues, so it won't work without it.

The only workaround to this would be to enable issues for the repo. Otherwise, I'm afraid this action will not work in this scenario.

**Comment by yashwanth-bit** [comment]
Hi Trstringer,

Thank you for the info 

Could you please guide me on how to enable the issues for the repository

**Comment by trstringer** [comment]
If you navigate to the repo's **Settings**, you'll scroll down and see the **Features** heading. There's a check box for **Issues**, you just have to check that. Here's the docs on how to [disable issues](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues), and doing the opposite is just making sure that box is checked.

**Comment by yashwanth-bit** [comment]
Thank you for the info
