### ISSUE TITLE
How to continue even if the issue is canceled

### ISSUE THREAD

**Issue by toa-lee** [trstringer/manual-approval#65]
hello trstringer
If the approval is yes, I would like to continue the distribution and if the approval is no, I would like to create a pipeline that rolls back to the previous image.
However, it is difficult because the pipeline is interrupted when you enter the no.
Is it possible?
Thank you so much and I hope you're always happy

**Comment by trstringer** [comment]
I believe you should be able to accomplish this with a follow on step to check if the manual-approval step failed. Here is [some documentation on failure()](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-status-check-functions).

Let me know if that answers your question!

**Comment by toa-lee** [comment]
hello trstringer

I solved this problem with your help.
Thank you so much
I hope you are always happy and full of blessings

**Comment by trstringer** [comment]
I am happy to hear that, and glad you were able to solve it!
