### ISSUE TITLE
Readme is not up to date with `v1.8.0` tag

### ISSUE THREAD

**Issue by b3nk3** [trstringer/manual-approval#76]
Hi there, just a notice, that you have changes and documentation in the readme, that is not reflective of the latest release which I found a bit confusing.

I was trying to use `issue-body` but in fact `v1.8.0`  does not have this functionality.

Are you planning on releasing it?

**Comment by cterence** [comment]
+1 on this, I spent a while trying to debug why this wasn't working.
I tried targetting the commit (948dfe9537d89917bd12e8a6868a28f83400fb32) where the functionality should be deployed but I couldn't make it work.

**Comment by trstringer** [comment]
Sorry for the delay on the v1.9.0 release (which includes `issue-body`). That's available now! As a point of reference, though, I have to manually do a release so the main branch might be (and usually is) ahead of the latest release.
